name = "pm-daily"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "pm-daily"
database_id = "4ed77142-3bd9-4a1b-9378-e8b527266066"
migrations_dir = "src/lib/server/db/migrations"

[[kv_namespaces]]
binding = "KV"
id = "845380d9438543e8a62871db136ddca0"

[[vectorize]]
binding = "VECTORIZE"
index_name = "lennys_metadata"

[[durable_objects.bindings]]
name = "QUIZ_SESSION"
class_name = "QuizSession"
script_name = "pm-daily"

[[migrations]]
tag = "v1"
new_classes = ["QuizSession"]

[triggers]
crons = ["* * * * *"]
